# Generated by Django 5.1.2 on 2024-10-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('published_date', models.DateField()),
                ('isbn_number', models.CharField(max_length=13)),
                ('number_of_pages', models.IntegerField()),
                ('book_cover', models.URLField(max_length=255)),
                ('language', models.CharField(max_length=50)),
            ],
        ),
    ]
